# Generated by Django 4.2.7 on 2025-12-15 21:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=256, unique=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, help_text='Краткое описание категории', verbose_name='Описание')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL', max_length=64, unique=True, verbose_name='Slug')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть категорию', verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'категория',
                'verbose_name_plural': 'Категории',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(max_length=256, unique=True, verbose_name='Название места')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
            ],
            options={
                'verbose_name': 'локация',
                'verbose_name_plural': 'Локации',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('title', models.CharField(max_length=256, verbose_name='Заголовок')),
                ('text', models.TextField(help_text='Основное содержание поста', verbose_name='Текст')),
                ('slug', models.SlugField(help_text='Уникальный идентификатор для URL', max_length=256, unique=True, verbose_name='Slug')),
                ('pub_date', models.DateTimeField(db_index=True, help_text='Если установить будущее время, пост будет опубликован в указанный момент', verbose_name='Дата и время публикации')),
                ('is_published', models.BooleanField(default=True, help_text='Снимите галочку, чтобы скрыть публикацию', verbose_name='Опубликовано')),
                ('image', models.ImageField(blank=True, help_text='Основное изображение поста', null=True, upload_to='posts/images/%Y/%m/%d/', verbose_name='Изображение')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор публикации')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.category', verbose_name='Категория')),
                ('location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='posts', to='posts.location', verbose_name='Местоположение')),
            ],
            options={
                'verbose_name': 'публикация',
                'verbose_name_plural': 'Публикации',
                'ordering': ['-pub_date', '-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='location',
            index=models.Index(fields=['name', 'is_published'], name='posts_locat_name_e0b335_idx'),
        ),
        migrations.AddIndex(
            model_name='category',
            index=models.Index(fields=['slug', 'is_published'], name='posts_categ_slug_709aa9_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['-pub_date', 'is_published'], name='posts_post_pub_dat_cf03a6_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['slug'], name='posts_post_slug_59b922_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['category', '-pub_date'], name='posts_post_categor_3ebfaa_idx'),
        ),
    ]
